name: Swift

on:
  workflow_call:

jobs:
  cancel_previous:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.9.1
      with:
        workflow_id: ${{ github.event.workflow.id }}

  build_and_test_examples:
    needs: cancel_previous
    runs-on: macOS-12
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0'
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: /Users/runner/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-examples-${{ hashFiles('**/Package.resolved') }}
        restore-keys: ${{ runner.os }}-spm-examples
    - name: build for ios simulator
      run: |
        cd Example/BasicExample
        xcodebuild -workspace "BasicExample.xcodeproj/project.xcworkspace" -scheme "BasicExample" -sdk iphonesimulator
