# On merge to main

name: Release Automation

on:
  push:
    branches:
      - main

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v3
    - name: version
      id: version
      run: echo "version=$(cat Sources/SegmentSprig/Version.swift | grep "__destination_version" | cut -d'=' -f2 | tr -d ' "')" >> $GITHUB_OUTPUT
  get-tag:
    runs-on: ubuntu-latest
    needs: get-version
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
    - name: tag
      id: tag
      run: echo "tag=v${{ needs.get-version.outputs.version }}" >> $GITHUB_OUTPUT
  create-release-and-tag:
    needs: get-tag
    uses: UserLeap/common-workflows/.github/workflows/_generic_create_release_tag.yml@main
    with:
      tag: ${{ needs.get-tag.outputs.tag }}
      release_url: https://api.github.com/repos/UserLeap/analytics-swift-sprig/releases
    secrets: inherit
  build-swift:
    if: ${{ needs.create-release-and-tag.outputs.new-tag == 'true' }}
    needs: [create-release-and-tag,get-version]
    uses: UserLeap/analytics-swift-sprig/.github/workflows/swift.yml@main
    secrets: inherit
